--
-- PostgreSQL database dump
--

\restrict LZRMNfuU5ybaU7eHyZb05v6Bm9Sz9PGb3MgwxJWGIrw965zjX88gT6xBFf4NI2u

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: snippets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.snippets (
    id integer NOT NULL,
    title character varying(100) NOT NULL,
    content text NOT NULL,
    created timestamp without time zone NOT NULL,
    expires timestamp without time zone NOT NULL
);


ALTER TABLE public.snippets OWNER TO postgres;

--
-- Name: snippets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.snippets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.snippets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: snippets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.snippets (id, title, content, created, expires) FROM stdin;
1	An old silent pond	An old silent pond...\\nA frog jumps into the pond,\\nsplash! Silence again.\\n\\n– Matsuo Bashō	2026-06-18 22:05:15.751546	2027-06-18 22:05:15.751546
2	Over the wintry forest	Over the wintry\\nforest, winds howl in rage\\nwith no leaves to blow.\\n\\n– Natsume Soseki	2026-06-18 22:05:15.764428	2027-06-18 22:05:15.764428
3	First autumn morning	First autumn morning\\nthe mirror I stare into\\nshows my father's face.\\n\\n– Murakami Kijo	2026-06-18 22:05:15.766131	2026-06-25 22:05:15.766131
\.


--
-- Name: snippets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.snippets_id_seq', 3, true);


--
-- Name: snippets snippets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.snippets
    ADD CONSTRAINT snippets_pkey PRIMARY KEY (id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO web;


--
-- Name: TABLE snippets; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.snippets TO web;


--
-- Name: SEQUENCE snippets_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,USAGE ON SEQUENCE public.snippets_id_seq TO web;


--
-- PostgreSQL database dump complete
--

\unrestrict LZRMNfuU5ybaU7eHyZb05v6Bm9Sz9PGb3MgwxJWGIrw965zjX88gT6xBFf4NI2u
